// Dev-only story page for the briefing board: `npm run dev:web`, then open /features/agent/workmap/demo.html.
// Two snapshots of the synthetic customer_07 session (generated by fixtures/generate.ts through packages/agent): the start
// of Review with open gaps, and the confirmed map after the teach-back. Query: ?stage=draft|confirmed&select=<card key>.
import { StrictMode, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import type { ScreenEvidence, ScreenObservation } from '@apprentice/contracts';
import draftRaw from './fixtures/board-draft.json?raw';
import confirmedRaw from './fixtures/board-confirmed.json?raw';
import { WorkMapBoard } from './WorkMapBoard.tsx';
import { syntheticEvidenceResolver } from './synthetic-frames.ts';
import type { BoardBlocker, Question, WorkMap } from './model.ts';

interface Snapshot {
  stage: string;
  sessionId: string;
  map: WorkMap;
  observations: ScreenObservation[];
  evidence: ScreenEvidence[];
  gaps: Question[];
  blockers: BoardBlocker[];
}

const SNAPSHOTS: Record<'draft' | 'confirmed', Snapshot> = {
  draft: JSON.parse(draftRaw) as Snapshot,
  confirmed: JSON.parse(confirmedRaw) as Snapshot,
};

const params = new URLSearchParams(location.search);
const initialStage = params.get('stage') === 'confirmed' ? 'confirmed' : 'draft';
const initialSelection = params.get('select');

const shell: React.CSSProperties = { maxWidth: 1320, margin: '0 auto', padding: 'clamp(16px, 3vw, 28px)', fontFamily: 'system-ui, sans-serif' };
const bar: React.CSSProperties = {
  display: 'flex', flexWrap: 'wrap', alignItems: 'center', gap: 10, marginBottom: 16, fontSize: 13, color: 'var(--demo-muted, #4f605c)',
};

function Demo() {
  const [stage, setStage] = useState<'draft' | 'confirmed'>(initialStage);
  const [log, setLog] = useState<string[]>([]);
  const snap = SNAPSHOTS[stage];
  const resolve = useMemo(() => syntheticEvidenceResolver(snap.observations, snap.evidence), [snap]);
  const push = (line: string) => setLog((l) => [line, ...l].slice(0, 4));
  return (
    <div style={shell}>
      <div style={bar}>
        <strong style={{ color: 'inherit' }}>Dev story · briefing board</strong>
        <span>Synthetic customer_07 session, played through packages/agent.</span>
        <span style={{ marginLeft: 'auto', display: 'inline-flex', gap: 6 }}>
          {(['draft', 'confirmed'] as const).map((s) => (
            <button
              key={s}
              type="button"
              onClick={() => setStage(s)}
              aria-pressed={stage === s}
              style={{
                font: 'inherit', padding: '4px 10px', borderRadius: 8, cursor: 'pointer',
                border: '1px solid #0a766f', background: stage === s ? '#0a766f' : 'transparent', color: stage === s ? '#fff' : '#0a766f',
              }}
            >
              {s === 'draft' ? 'Start of Review' : 'After teach-back'}
            </button>
          ))}
        </span>
      </div>
      <WorkMapBoard
        key={stage}
        map={snap.map}
        observations={snap.observations}
        evidence={snap.evidence}
        gaps={snap.gaps}
        blockers={snap.blockers}
        resolveEvidence={resolve}
        synthetic
        title="customer_07 · delivery details email"
        initialSelection={initialSelection}
        onSeek={(id, start, end) => push(`onSeek(${id}, ${start}, ${end})`)}
        onConfirmRequest={(item) => push(`onConfirmRequest(${item.kind} ${item.id})`)}
        onGapSelect={(gap) => push(`onGapSelect(${gap.id})`)}
      />
      <pre data-demo-log style={{ marginTop: 16, fontSize: 12, color: '#4f605c', whiteSpace: 'pre-wrap' }}>
        {log.length > 0 ? log.join('\n') : 'Callbacks appear here.'}
      </pre>
    </div>
  );
}

const root = document.getElementById('root');
if (root) createRoot(root).render(<StrictMode><Demo /></StrictMode>);
