// Readers for the board fixtures (generated by ../fixtures/generate.ts from the synthetic customer_07 session).
import { readFileSync } from 'node:fs';
import type { ScreenEvidence, ScreenObservation } from '@apprentice/contracts';
import type { BoardBlocker, Question, WorkMap } from '../model.ts';

export interface Snapshot {
  stage: string;
  synthetic: boolean;
  map: WorkMap;
  observations: ScreenObservation[];
  evidence: ScreenEvidence[];
  gaps: Question[];
  blockers: BoardBlocker[];
}

export function snapshot(stage: 'draft' | 'confirmed'): Snapshot {
  return JSON.parse(readFileSync(new URL(`../fixtures/board-${stage}.json`, import.meta.url), 'utf8')) as Snapshot;
}

/** A deep, mutable copy of a snapshot, for tests that change one item. */
export function mutable(stage: 'draft' | 'confirmed'): Snapshot {
  return structuredClone(snapshot(stage));
}
